# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./MayaMaker/MayaMaker.Services/MayaMaker.Services.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/MayaMaker/MayaMaker.Services/bin/Release/netcoreapp3.1/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SalfordConnection'
    appType: 'webAppLinux'
    WebAppName: 'mayamaker'
    packageForLinux: '$(System.ArtifactsDirectory)/drop'
    RuntimeStack: 'DOTNETCORE|3.1'
    StartupCommand: 'dotnet MayaMaker.Services.dll'